-- 問題テーブル
-- answer: true=○（マル） / false=×（バツ）
CREATE TABLE questions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text        VARCHAR(500)  NOT NULL,
    answer      BOOLEAN       NOT NULL,
    explanation VARCHAR(1000),
    created_at  TIMESTAMP     NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP     NOT NULL DEFAULT now()
);
