-- ============================================================
-- スミカ不動産 シードデータ(tools/export-seed.js により自動生成)
-- 生成日: 2026-07-07
-- ============================================================

BEGIN;
TRUNCATE rooms, buildings;

INSERT INTO buildings (id, name, type, address, access, built_year, structure, total_floors, total_units, note) VALUES ('b01', '幸荘(さいわいそう)', 'apartment', '東京都青葉川区仲宿町3-14-8', '[{"line":"東都線","station":"仲宿","walk":18},{"line":"青葉川バス「仲宿三丁目」","station":"停留所","walk":4}]'::jsonb, 1974, '木造', 2, 8, '昭和の風情が残る味わい深いアパート。家賃重視の方に。');
INSERT INTO buildings (id, name, type, address, access, built_year, structure, total_floors, total_units, note) VALUES ('b02', 'コーポ久保田', 'apartment', '東京都青葉川区栄町1-22-6', '[{"line":"東都線","station":"青葉川","walk":14}]'::jsonb, 1988, '木造', 2, 6, '商店街そば。生活利便性は良好な昔ながらのアパート。');
INSERT INTO buildings (id, name, type, address, access, built_year, structure, total_floors, total_units, note) VALUES ('b03', 'メゾン・ド・たんぽぽ', 'apartment', '神奈川県湊川市白鳥台2-8-15', '[{"line":"湊川線","station":"白鳥台","walk":10}]'::jsonb, 1997, '軽量鉄骨造', 2, 10, '敷地内駐車場ありの郊外型アパート。ファミリーにも。');
INSERT INTO buildings (id, name, type, address, access, built_year, structure, total_floors, total_units, note) VALUES ('b04', 'ハイツ青葉台II', 'apartment', '東京都青葉川区青葉台4-6-21', '[{"line":"東都線","station":"青葉台","walk":7}]'::jsonb, 2009, '軽量鉄骨造', 2, 8, '小型犬飼育相談可。手頃な賃料と設備のバランスが良い一棟。');
INSERT INTO buildings (id, name, type, address, access, built_year, structure, total_floors, total_units, note) VALUES ('b05', 'グランメール藤沢台', 'mansion', '東京都藤沢台区本町2-11-3', '[{"line":"都心環状線","station":"藤沢台","walk":9}]'::jsonb, 2005, 'RC(鉄筋コンクリート)造', 7, 28, '管理良好な中規模マンション。単身〜二人暮らしに人気。');
INSERT INTO buildings (id, name, type, address, access, built_year, structure, total_floors, total_units, note) VALUES ('b06', 'パークサイド千歳レジデンス', 'mansion', '東京都千歳野区千歳公園1-3-12', '[{"line":"都心環状線","station":"千歳野","walk":6},{"line":"東都線","station":"千歳公園","walk":11}]'::jsonb, 2014, 'RC(鉄筋コンクリート)造', 10, 45, '公園隣接・ペット可(小型犬・猫)。敷地内駐車場あり。');
INSERT INTO buildings (id, name, type, address, access, built_year, structure, total_floors, total_units, note) VALUES ('b07', 'ルミエール桜ヶ丘', 'mansion', '東京都桜ヶ丘区桜通り5-2-9', '[{"line":"桜ヶ丘線","station":"桜ヶ丘","walk":4}]'::jsonb, 2022, 'RC(鉄筋コンクリート)造', 8, 32, '築浅・インターネット無料・宅配ボックス完備のデザイナーズ。');
INSERT INTO buildings (id, name, type, address, access, built_year, structure, total_floors, total_units, note) VALUES ('b08', 'セレスティアタワー湊風', 'tower', '東京都湾岸区湊風1-1-1', '[{"line":"湾岸線","station":"湊風","walk":5},{"line":"都心環状線","station":"湾岸中央","walk":12}]'::jsonb, 2019, 'SRC(鉄骨鉄筋コンクリート)造', 38, 320, '運河沿いの38階建てタワー。スカイラウンジ・フィットネス完備。');
INSERT INTO buildings (id, name, type, address, access, built_year, structure, total_floors, total_units, note) VALUES ('b09', 'ザ・グランスカイタワー中央', 'tower', '東京都中央川区大手町通り2-1-1', '[{"line":"都心環状線","station":"中央川","walk":3},{"line":"東都線","station":"大手町通り","walk":1,"note":"駅直結"}]'::jsonb, 2024, 'SRC(鉄骨鉄筋コンクリート)造', 52, 480, '駅直結52階建て。コンシェルジュ・ゲストルーム・プール併設の最高級レジデンス。');

INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0101', 'b01', '101', 1, '1K', 16.5, '北', 25000, 1000, 0, 0, '', false, '["敷金なし","礼金なし","和室","プロパンガス"]'::jsonb, 'とにかく家賃を抑えたい方へ。昭和49年築、味のある和室6畳のお部屋です。水回りは年季が入っていますが、その分この賃料。共用廊下の床は少しきしみますが、大家さんが月1回掃除に来てくれます。', '["images/rooms/r0101.svg","images/buildings/b01.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0102', 'b01', '103', 1, '1K', 16.5, '南', 28000, 1000, 1, 0, '', true, '["礼金なし","和室","ペット相談可","プロパンガス","庭付き"]'::jsonb, '1階南向き・小さな専用庭付き。古いお部屋ですがペット相談可(小型犬・猫1匹まで)は貴重です。畳は入居時に表替え済み。ガス給湯器は3年前に交換済みで、お湯はすぐ出ます。', '["images/rooms/r0102.svg","images/buildings/b01.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0103', 'b01', '201', 2, '2K', 28, '南', 38000, 2000, 1, 1, '', false, '["和室","2人入居可","プロパンガス","日当たり良好"]'::jsonb, '2階角の2K。和室4.5畳+6畳で、二人入居も相談可能です。南向きで日当たりは抜群。窓サッシは古く冬はやや冷えますが、家賃を考えれば十分の住み心地です。', '["images/rooms/r0103.svg","images/buildings/b01.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0104', 'b01', '203', 2, '1K', 17, '西', 27000, 1000, 0, 0, '', false, '["敷金なし","礼金なし","和室","プロパンガス"]'::jsonb, '初期費用を最小限に抑えられる敷金・礼金なしのお部屋。西日がよく入るので冬は意外と暖かいです。壁の一部にへこみがありますが、その分家賃はご近所最安クラス。', '["images/rooms/r0104.svg","images/buildings/b01.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0201', 'b02', '102', 1, '1DK', 25.5, '東', 42000, 2000, 1, 0, '', false, '["礼金なし","和室","都市ガス","商店街近く"]'::jsonb, '徒歩2分の栄町商店街が生活の味方。夕方はお惣菜の値引きも。DK部分は板張り、居室は和室6畳です。給湯器・ガスコンロは交換済み。', '["images/rooms/r0201.svg","images/buildings/b02.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0202', 'b02', '201', 2, '1DK', 26, '南東', 47000, 2000, 1, 1, '', false, '["フローリング","都市ガス","リフォーム済","2階以上"]'::jsonb, '2023年に室内リフォーム済み。和室をフローリングに変更し、壁紙も一新しました。築年数を感じさせない室内です。外観は昔ながらですが、中はきれい。コスパ重視の方におすすめ。', '["images/rooms/r0202.svg","images/buildings/b02.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0203', 'b02', '202', 2, '2DK', 38, '南', 52000, 3000, 1, 1, '', false, '["和室","2人入居可","都市ガス","日当たり良好","2階以上"]'::jsonb, 'この賃料で2DK・38㎡はなかなか出ません。和室2間続きで、ふすまを開ければ広々ワンルームのようにも使えます。二人暮らしのスタートにどうぞ。', '["images/rooms/r0203.svg","images/buildings/b02.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0204', 'b02', '103', 1, '1K', 19.5, '北東', 39000, 2000, 0, 0, '', false, '["敷金なし","礼金なし","フローリング","都市ガス"]'::jsonb, '敷金・礼金ゼロで初期費用を抑えられる1K。北東向きで夏は涼しく過ごせます。室内洗濯機置場あり(防水パンは小型サイズ)。単身の方の仮住まいにも人気です。', '["images/rooms/r0204.svg","images/buildings/b02.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0301', 'b03', '101', 1, '2DK', 40.5, '南', 55000, 3000, 1, 0, '敷地内 5,000円/月', false, '["礼金なし","駐車場あり","フローリング","都市ガス","専用庭"]'::jsonb, '敷地内駐車場が月5,000円と格安。1階専用庭付きで、ガーデニングや子どもの遊び場に。小学校まで徒歩5分の子育て環境です。', '["images/rooms/r0301.svg","images/buildings/b03.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0302', 'b03', '203', 2, '2DK', 40.5, '南', 58000, 3000, 1, 1, '敷地内 5,000円/月', false, '["駐車場あり","フローリング","都市ガス","日当たり良好","2階以上","バス・トイレ別"]'::jsonb, '2階南向きで日当たり・風通しとも良好。バス・トイレ別、独立した洗面スペースありで、築年数の割に水回りが使いやすい間取りです。', '["images/rooms/r0302.svg","images/buildings/b03.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0303', 'b03', '105', 1, '1DK', 29, '東', 45000, 3000, 1, 0, '敷地内 5,000円/月', true, '["礼金なし","駐車場あり","ペット相談可","フローリング","バス・トイレ別"]'::jsonb, '小型犬・猫飼育相談可(1匹まで・敷金1ヶ月積み増し)。近くに白鳥台中央公園があり、お散歩コースに困りません。車+ペットの暮らしを手頃に実現できます。', '["images/rooms/r0303.svg","images/buildings/b03.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0304', 'b03', '206', 2, '3DK', 52, '南西', 63000, 3000, 2, 1, '敷地内 5,000円/月', false, '["駐車場あり","フローリング","2人入居可","2階以上","バス・トイレ別","追い焚き"]'::jsonb, 'ファミリー向け3DK。全居室に窓があり明るいお部屋です。2020年に給湯器を追い焚き付きに交換済み。この広さと駐車場込みでこの価格は郊外ならでは。', '["images/rooms/r0304.svg","images/buildings/b03.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0401', 'b04', '101', 1, '1K', 23, '南', 62000, 3000, 1, 1, '', false, '["フローリング","バス・トイレ別","独立洗面台","都市ガス","エアコン付"]'::jsonb, '単身者に人気の設備充実1K。バス・トイレ別+独立洗面台で朝の支度がスムーズ。駅徒歩7分、コンビニ徒歩1分の便利な立地です。', '["images/rooms/r0401.svg","images/buildings/b04.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0402', 'b04', '202', 2, '1LDK', 33.5, '南', 75000, 4000, 1, 1, '近隣 12,000円/月', true, '["ペット相談可","フローリング","バス・トイレ別","独立洗面台","2階以上","エアコン付","宅配ボックス"]'::jsonb, '小型犬1匹まで飼育相談可の1LDK。LDK10帖+洋室6帖のゆとりある間取り。2階角部屋で足音を気にせずペットと暮らせます。宅配ボックスも後付け設置済み。', '["images/rooms/r0402.svg","images/buildings/b04.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0403', 'b04', '103', 1, '1K', 22.5, '東', 58000, 3000, 1, 0, '', false, '["礼金なし","フローリング","バス・トイレ別","都市ガス","エアコン付"]'::jsonb, '礼金なしの東向き1K。朝日で気持ちよく目覚められるお部屋です。室内は白基調で清潔感があり、女性の入居者も多い一棟です。', '["images/rooms/r0403.svg","images/buildings/b04.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0404', 'b04', '205', 2, '2LDK', 45, '南西', 89000, 4000, 1, 1, '近隣 12,000円/月', false, '["フローリング","バス・トイレ別","独立洗面台","2人入居可","2階以上","追い焚き","エアコン付"]'::jsonb, 'アパートながら2LDK・45㎡の広さ。カウンターキッチンと追い焚き付きバスで、マンション顔負けの設備です。二人暮らし・新婚さんに。', '["images/rooms/r0404.svg","images/buildings/b04.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0501', 'b05', '203', 2, '1K', 24.5, '東', 72000, 6000, 1, 1, '', false, '["オートロック","バス・トイレ別","独立洗面台","フローリング","エアコン付","2階以上"]'::jsonb, 'オートロック付きRCマンションの1K。上下階の音が響きにくい鉄筋コンクリート造で、在宅ワークにも向いています。管理人が週3日巡回しており共用部はいつも清潔。', '["images/rooms/r0501.svg","images/buildings/b05.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0502', 'b05', '405', 4, '1LDK', 36, '南', 88000, 7000, 1, 1, '', false, '["オートロック","バス・トイレ別","独立洗面台","宅配ボックス","フローリング","2階以上","エアコン付"]'::jsonb, '4階南向きの明るい1LDK。前面に高い建物がなく、眺望・採光良好です。宅配ボックス完備で不在時の荷物受け取りも安心。', '["images/rooms/r0502.svg","images/buildings/b05.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0503', 'b05', '601', 6, '2LDK', 55, '南東', 98000, 8000, 2, 1, '', false, '["オートロック","バス・トイレ別","追い焚き","浴室乾燥機","角部屋","2人入居可","2階以上","エアコン付"]'::jsonb, '6階南東角部屋の2LDK。二面採光で風通し抜群。追い焚き+浴室乾燥機付きで雨の日の洗濯も安心です。ファミリー・DINKSに。', '["images/rooms/r0503.svg","images/buildings/b05.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0504', 'b05', '302', 3, '1DK', 30, '西', 78000, 6000, 1, 0, '', false, '["礼金なし","オートロック","バス・トイレ別","独立洗面台","リフォーム済","2階以上","エアコン付"]'::jsonb, '2025年リフォーム済み・礼金なし。キッチンと洗面台を新品交換し、築年数を感じない室内に生まれ変わりました。夕日がきれいな西向きです。', '["images/rooms/r0504.svg","images/buildings/b05.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0601', 'b06', '305', 3, '1LDK', 40, '南', 105000, 8000, 1, 1, '敷地内 18,000円/月', true, '["ペット可","駐車場あり","オートロック","宅配ボックス","バス・トイレ別","独立洗面台","浴室乾燥機","2階以上","エアコン付"]'::jsonb, '小型犬・猫2匹まで飼育可(敷金1ヶ月積み増し)。目の前が千歳公園で、朝のお散歩が日課になります。1階に足洗い場あり。ペットと暮らすための設計が随所に。', '["images/rooms/r0601.svg","images/buildings/b06.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0602', 'b06', '702', 7, '2LDK', 58.5, '南東', 135000, 10000, 1, 1, '敷地内 18,000円/月', true, '["ペット可","駐車場あり","オートロック","宅配ボックス","追い焚き","浴室乾燥機","床暖房","角部屋","2階以上","エアコン付"]'::jsonb, '7階角部屋・公園ビューの2LDK。リビング床暖房+追い焚き付きで冬も快適。窓から千歳公園の緑を一望でき、季節の移ろいを感じられるお部屋です。', '["images/rooms/r0602.svg","images/buildings/b06.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0603', 'b06', '201', 2, '1K', 26, '東', 85000, 7000, 1, 0, '', false, '["礼金なし","オートロック","宅配ボックス","バス・トイレ別","独立洗面台","2階以上","エアコン付"]'::jsonb, '礼金なしの築浅感ある1K。26㎡と単身向けにしてはゆとりがあり、テレワーク用デスクも置けます。共用部の植栽が美しい、管理の行き届いたマンションです。', '["images/rooms/r0603.svg","images/buildings/b06.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0604', 'b06', '805', 8, '3LDK', 72, '南', 168000, 12000, 2, 1, '敷地内 18,000円/月', true, '["ペット可","駐車場あり","オートロック","宅配ボックス","追い焚き","浴室乾燥機","床暖房","2人入居可","2階以上","エアコン付"]'::jsonb, 'ファミリー向け3LDK・72㎡。全居室収納付き+ウォークインクローゼットで収納力抜群。学区の千歳小学校は徒歩6分。ペットも家族も伸び伸び暮らせます。', '["images/rooms/r0604.svg","images/buildings/b06.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0605', 'b06', '506', 5, '2DK', 48, '西', 112000, 8000, 1, 1, '', false, '["オートロック","宅配ボックス","バス・トイレ別","独立洗面台","追い焚き","2人入居可","2階以上","エアコン付"]'::jsonb, '使い勝手の良い2DK。ダイニングキッチンが10帖あり、実質1LDKのように使えます。夕焼けがきれいな西向きバルコニーはガーデニングにも。', '["images/rooms/r0605.svg","images/buildings/b06.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0701', 'b07', '202', 2, '1K', 26.5, '南', 105000, 10000, 1, 1, '', false, '["インターネット無料","オートロック","宅配ボックス","バス・トイレ別","独立洗面台","浴室乾燥機","デザイナーズ","2階以上","エアコン付"]'::jsonb, '築浅デザイナーズの1K。コンクリート打ちっぱなしの壁と間接照明レールがおしゃれな室内。インターネット無料(1Gbps)で開通工事も不要です。', '["images/rooms/r0701.svg","images/buildings/b07.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0702', 'b07', '503', 5, '1LDK', 42, '南', 138000, 12000, 1, 1, '', false, '["インターネット無料","オートロック","宅配ボックス","追い焚き","浴室乾燥機","床暖房","デザイナーズ","2階以上","エアコン付","カウンターキッチン"]'::jsonb, '駅徒歩4分・築4年の1LDK。アイランド風カウンターキッチンが主役の、料理が楽しくなるお部屋です。桜ヶ丘駅前の再開発エリアで、商業施設も充実。', '["images/rooms/r0702.svg","images/buildings/b07.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0703', 'b07', '801', 8, '2LDK', 60, '南西', 160000, 14000, 2, 1, '近隣 25,000円/月', false, '["インターネット無料","オートロック","宅配ボックス","追い焚き","浴室乾燥機","床暖房","角部屋","最上階","デザイナーズ","エアコン付"]'::jsonb, '最上階南西角の2LDK。桜通りの桜並木を見下ろすバルコニーは、春には特等席になります。天井高2.6mのゆとりある空間設計。', '["images/rooms/r0703.svg","images/buildings/b07.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0704', 'b07', '304', 3, '1DK', 32, '東', 118000, 10000, 1, 0, '', false, '["礼金なし","インターネット無料","オートロック","宅配ボックス","バス・トイレ別","独立洗面台","浴室乾燥機","デザイナーズ","2階以上","エアコン付"]'::jsonb, '礼金なしキャンペーン中の1DK。土間風の玄関スペースが特徴で、自転車や観葉植物を置くのも◎。個性的な間取りがお好きな方へ。', '["images/rooms/r0704.svg","images/buildings/b07.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0801', 'b08', '1205', 12, '1LDK', 45, '東', 165000, 15000, 1, 1, '敷地内(機械式) 35,000円/月', true, '["タワーマンション","ペット可","駐車場あり","オートロック","コンシェルジュ","宅配ボックス","追い焚き","浴室乾燥機","床暖房","フィットネス","エアコン付"]'::jsonb, '12階東向き、運河を望む1LDK。朝は水面に反射する朝日が室内を満たします。24時間有人管理+コンシェルジュサービス(クリーニング取次など)付き。', '["images/rooms/r0801.svg","images/buildings/b08.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0802', 'b08', '2103', 21, '2LDK', 62, '南', 235000, 20000, 2, 1, '敷地内(機械式) 35,000円/月', true, '["タワーマンション","ペット可","駐車場あり","オートロック","コンシェルジュ","宅配ボックス","追い焚き","浴室乾燥機","床暖房","眺望良好","フィットネス","エアコン付"]'::jsonb, '21階南向き2LDK。レインボーカラーにライトアップされる湾岸の夜景が毎晩の楽しみに。ディスポーザー・食洗機・タンクレストイレと設備もフルスペック。', '["images/rooms/r0802.svg","images/buildings/b08.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0803', 'b08', '3002', 30, '2LDK', 68.5, '南西', 280000, 25000, 2, 2, '敷地内(機械式) 35,000円/月', true, '["タワーマンション","ペット可","駐車場あり","オートロック","コンシェルジュ","宅配ボックス","追い焚き","浴室乾燥機","床暖房","角部屋","眺望良好","フィットネス","エアコン付"]'::jsonb, '30階南西角住戸。リビングのワイドサッシから海と都心のビル群を一望できます。35階のスカイラウンジ、3階のフィットネスジム(24時間)は住人無料。', '["images/rooms/r0803.svg","images/buildings/b08.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0804', 'b08', '905', 9, '1K', 30, '北', 125000, 12000, 1, 1, '', false, '["タワーマンション","オートロック","コンシェルジュ","宅配ボックス","バス・トイレ別","独立洗面台","浴室乾燥機","フィットネス","エアコン付"]'::jsonb, 'タワーライフを手の届く価格で。9階北向きは直射日光が少なく、夏も涼しく在宅ワークに最適。共用施設(ラウンジ・ジム・ゲストルーム)はすべて利用可能です。', '["images/rooms/r0804.svg","images/buildings/b08.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0805', 'b08', '3501', 35, '3LDK', 85, '南', 350000, 30000, 2, 2, '敷地内(平置き) 45,000円/月', true, '["タワーマンション","ペット可","駐車場あり","オートロック","コンシェルジュ","宅配ボックス","追い焚き","浴室乾燥機","床暖房","眺望良好","高層階","フィットネス","エアコン付"]'::jsonb, '35階・スカイラウンジと同フロアのプレミアム3LDK。85㎡の広さに加え、天井高2.7m・複層ガラス・全室床暖房。花火大会の日は自宅が特等席になります。', '["images/rooms/r0805.svg","images/buildings/b08.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0901', 'b09', '1808', 18, '1LDK', 50, '東', 250000, 25000, 2, 1, '敷地内(機械式) 50,000円/月', true, '["タワーマンション","駅直結","ペット可","駐車場あり","オートロック","コンシェルジュ","宅配ボックス","追い焚き","浴室乾燥機","床暖房","フィットネス","プール","エアコン付"]'::jsonb, '駅直結・雨に濡れずに帰宅できる18階1LDK。ホテルライクな内廊下設計で、廊下には絨毯とアートが。スマートキー+顔認証エントランスの最新セキュリティ。', '["images/rooms/r0901.svg","images/buildings/b09.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0902', 'b09', '2704', 27, '2LDK', 70, '南東', 380000, 35000, 2, 2, '敷地内(機械式) 50,000円/月', true, '["タワーマンション","駅直結","ペット可","駐車場あり","コンシェルジュ","宅配ボックス","追い焚き","浴室乾燥機","床暖房","眺望良好","フィットネス","プール","エアコン付"]'::jsonb, '27階南東向き2LDK。LDK20帖の大空間に、御影石カウンターのオーダーキッチン。共用部には25mプール・サウナ・ゲストスイートを完備しています。', '["images/rooms/r0902.svg","images/buildings/b09.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0903', 'b09', '3902', 39, '3LDK', 95, '南', 550000, 45000, 3, 2, '敷地内(平置き) 60,000円/月', true, '["タワーマンション","駅直結","ペット可","駐車場あり","コンシェルジュ","宅配ボックス","追い焚き","浴室乾燥機","床暖房","眺望良好","高層階","フィットネス","プール","エアコン付"]'::jsonb, '39階・95㎡の3LDK。バスルームからも夜景を望める贅沢な設計です。専属コンシェルジュによるハウスキーピング・タクシー手配などホテルサービスを日常に。', '["images/rooms/r0903.svg","images/buildings/b09.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0904', 'b09', '4501', 45, '3LDK', 110, '南西', 780000, 60000, 3, 2, '敷地内(平置き) 60,000円/月', true, '["タワーマンション","駅直結","ペット可","駐車場あり","コンシェルジュ","追い焚き","浴室乾燥機","床暖房","角部屋","眺望良好","高層階","フィットネス","プール","エアコン付"]'::jsonb, '45階南西角のエグゼクティブ住戸。二面のコーナーサッシが切り取る夕景は圧巻の一言。ワインセラー・ミーレ製食洗機・天然石の玄関と、細部まで一切妥協のない仕様です。', '["images/rooms/r0904.svg","images/buildings/b09.svg"]'::jsonb);
INSERT INTO rooms (id, building_id, room_no, floor, layout, area, direction, rent, management_fee, deposit, key_money, parking, pet, tags, description, images) VALUES ('r0905', 'b09', '5201', 52, '4LDK', 165, '南', 1500000, 100000, 6, 0, '専用2台(平置き) 無料', true, '["タワーマンション","駅直結","ペントハウス","ペット可","駐車場あり","コンシェルジュ","追い焚き","浴室乾燥機","床暖房","眺望良好","高層階","フィットネス","プール","ルーフバルコニー","エアコン付"]'::jsonb, '最上階52階・ワンフロア半分を占めるペントハウス。165㎡+50㎡のルーフバルコニー、天井高3.2m。専用エレベーターで玄関前まで直行できます。都心の全景を独り占めする、東京で数少ない賃貸最高峰の住まい。内見は事前審査制です。', '["images/rooms/r0905.svg","images/buildings/b09.svg"]'::jsonb);

COMMIT;
